(function(){"use strict";var c=window.WEDDING_CONFIG||{};function q(s,r){return(r||document).querySelector(s)}function qa(s,r){return Array.from((r||document).querySelectorAll(s))}function safe(fn){try{fn()}catch(e){console.warn("Mejora opcional no disponible",e)}}
function bind(){var m={monogram:c.couple.monogram,partner1:c.couple.partner1,partner2:c.couple.partner2,eyebrow:c.eyebrow,dateLabel:c.dateLabel,venueShort:c.venueShort,intro:c.intro,invitation:c.invitation,dressTitle:c.dressCode.title,dressText:c.dressCode.text,dressNote:c.dressCode.note,giftText:c.gifts.text,bank:c.gifts.bank,rsvpDeadline:c.rsvpDeadline};qa("[data-bind]").forEach(function(el){if(m[el.dataset.bind])el.textContent=m[el.dataset.bind]});q("[data-image=hero]").src=c.images.hero;q("[data-image=story]").src=c.images.story}
function opening(){var panel=q("#opening"),button=q("#openInvitation");document.body.style.overflow="hidden";function open(){panel.classList.add("is-open");document.body.style.overflow="";setTimeout(function(){panel.remove()},800)}button.addEventListener("click",open);setTimeout(function(){button.focus()},250);setTimeout(open,7000)}
function render(){q("#storyTimeline").innerHTML=c.story.map(function(x){return"<article><time>"+x.year+"</time><h3>"+x.title+"</h3><p>"+x.text+"</p></article>"}).join("");q("#galleryGrid").innerHTML=c.images.gallery.map(function(x,i){return'<figure><img src="'+x.src+'" style="object-position:'+x.position+'" alt="Mariana y Sebastián, momento '+(i+1)+'" width="900" height="1200" loading="lazy"><figcaption>0'+(i+1)+' · '+x.caption+"</figcaption></figure>"}).join("");q("#venueList").innerHTML=c.venues.map(function(v){return'<article class="place"><time>'+v.time+'</time><div><p class="kicker">'+v.detail+'</p><h3>'+v.name+'</h3><p>'+v.address+'</p></div><a href="'+v.maps+'" target="_blank" rel="noopener">Abrir ubicación</a></article>'}).join("");q("#schedule").innerHTML=c.itinerary.map(function(x){return"<article><time>"+x.time+"</time><h3>"+x.label+"</h3></article>"}).join("")}
function countdown(){var target=new Date(c.date).getTime();function tick(){var left=Math.max(0,target-Date.now()),v=[Math.floor(left/864e5),Math.floor(left/36e5)%24,Math.floor(left/6e4)%60,Math.floor(left/1e3)%60];["days","hours","minutes","seconds"].forEach(function(id,i){q("#"+id).textContent=String(v[i]).padStart(i?2:1,"0")})}tick();setInterval(tick,1000)}
function calendar(){var start=new Date(c.date),end=new Date(start.getTime()+7*36e5),pad=function(n){return String(n).padStart(2,"0")},utc=function(d){return d.getUTCFullYear()+pad(d.getUTCMonth()+1)+pad(d.getUTCDate())+"T"+pad(d.getUTCHours())+pad(d.getUTCMinutes())+pad(d.getUTCSeconds())+"Z"},title="Boda de "+c.couple.partner1+" y "+c.couple.partner2,location=c.venues[0].address,button=q("#calendarButton"),menu=q("#calendarMenu");q("#googleCalendar").href="https://calendar.google.com/calendar/render?action=TEMPLATE&text="+encodeURIComponent(title)+"&dates="+utc(start)+"/"+utc(end)+"&location="+encodeURIComponent(location);q("#outlookCalendar").href="https://outlook.live.com/calendar/0/deeplink/compose?subject="+encodeURIComponent(title)+"&startdt="+start.toISOString()+"&enddt="+end.toISOString()+"&location="+encodeURIComponent(location);button.addEventListener("click",function(){menu.hidden=!menu.hidden;button.setAttribute("aria-expanded",String(!menu.hidden))});q("#appleCalendar").addEventListener("click",function(){var data="BEGIN:VCALENDAR\r\nVERSION:2.0\r\nBEGIN:VEVENT\r\nDTSTART:"+utc(start)+"\r\nDTEND:"+utc(end)+"\r\nSUMMARY:"+title+"\r\nLOCATION:"+location+"\r\nEND:VEVENT\r\nEND:VCALENDAR",a=document.createElement("a");a.href=URL.createObjectURL(new Blob([data],{type:"text/calendar"}));a.download="boda-mariana-sebastian.ics";a.click();setTimeout(function(){URL.revokeObjectURL(a.href)},0)})}
function interactions(){q("#showBank").addEventListener("click",function(e){var el=q("#bankData");el.hidden=!el.hidden;e.currentTarget.textContent=el.hidden?"Ver información":"Ocultar información"});var form=q("#rsvpForm");form.addEventListener("submit",function(e){e.preventDefault();var data=Object.fromEntries(new FormData(form).entries());localStorage.setItem("wedding-rsvp",JSON.stringify(data));q("#rsvpStatus").textContent="¡Gracias! Tu respuesta quedó guardada en esta demo.";form.reset()});q("#whatsapp").href="https://wa.me/"+c.whatsapp+"?text="+encodeURIComponent(c.whatsappMessage)}
function motion(){var els=qa(".reveal"),o=new IntersectionObserver(function(entries){entries.forEach(function(x){if(x.isIntersecting){x.target.classList.add("is-visible");o.unobserve(x.target)}})},{threshold:.05});els.forEach(function(el){o.observe(el)});setTimeout(function(){els.forEach(function(el){el.classList.add("is-visible")})},1600)}
safe(bind);safe(render);safe(opening);safe(countdown);safe(calendar);safe(interactions);safe(motion)})();
